title = "Thinking Ape"
author = "Daryl Gubler"
description = "Occasional Code and Writings"
profilePicture = "images/brain_ape.png"
contentratio = 0.7
readMore = true
postSectionName = "posts"

customCss = ["css/custom.css", "css/syntax.css"]

keywords = ""
favicon = "favicons/"
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
singleDateFormat = "2006-01-02"
indexDateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/gubler"
